In [1]:
import numpy as np
def multiply_matrices(matrix1, matrix2):
    result=np.dot(matrix1, matrix2)
    return result
matrix_a=np.random.rand(3,3)
matrix_b=np.random.rand(3,3)
print("Matrix A:")
print(matrix_a)
print("\n Matrix B:")
print(matrix_b)
result_matrix=multiply_matrices(matrix_a,matrix_b)
print("\n Result Matrix:")
print(result_matrix)

Matrix A:
[[0.46690576 0.69695009 0.86674476]
 [0.41098427 0.71241652 0.44307207]
 [0.37250976 0.46752922 0.18474656]]

 Matrix B:
[[0.33205964 0.44655937 0.56937725]
 [0.45637028 0.35396457 0.94698688]
 [0.52425529 0.05312475 0.6057224 ]]

 Result Matrix:
[[0.92750339 0.50124238 1.45085482]
 [0.69387989 0.45923718 1.17703286]
 [0.43391626 0.34165112 0.76674775]]
